import {
    AddCustomerParamsSchema,
    AddCustomerResponseSchema,
    AddServiceProvidedParamsSchema,
    AddServiceProvidedResponseSchema,
    CustomerSchema,
    ErrorSchema,
    LoadUserCustomersResponseSchema,
    LoginParamsSchema,
    LoginResponseSchema,
    ServiceProvidedSchema,
    SignUpParamsSchema,
    SignUpResponseSchema,
    UserSchema,
} from "@/main/docs/schemas";

export const schemas = {
    loginParams: LoginParamsSchema,
    loginResponse: LoginResponseSchema,
    error: ErrorSchema,
    user: UserSchema,
    signUpParams: SignUpParamsSchema,
    signUpResponse: SignUpResponseSchema,
    addCustomerParams: AddCustomerParamsSchema,
    addCustomerResponse: AddCustomerResponseSchema,
    loadUserCustomersResponse: LoadUserCustomersResponseSchema,
    customer: CustomerSchema,
    addServiceProvidedParams: AddServiceProvidedParamsSchema,
    addServiceProvidedResponse: AddServiceProvidedResponseSchema,
    serviceProvided: ServiceProvidedSchema,
};
